"""Locates and loads the active profile's configuration.

Everything personal lives in profiles/<slug>/, generated by setup.py. The
active profile is named in profiles/ACTIVE. Legacy single-user installs, where
the YAML files sit at the project root, keep working: the loader falls back
there when no profile exists.
"""
from __future__ import annotations

import os

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROFILES_DIR = os.path.join(ROOT, "profiles")
ACTIVE_FILE = os.path.join(PROFILES_DIR, "ACTIVE")

CONFIG_FILES = ("config.yaml", "companies.yaml", "letters.yaml",
                "skills_taxonomy.yaml", "narrative.yaml")


class ProfileError(RuntimeError):
    """Raised when no usable configuration can be found."""


def active_profile() -> str:
    if os.path.exists(ACTIVE_FILE):
        with open(ACTIVE_FILE, "r", encoding="utf-8") as fh:
            name = fh.read().strip()
        if name and os.path.isdir(os.path.join(PROFILES_DIR, name)):
            return name
    if os.path.isdir(PROFILES_DIR):
        dirs = sorted(d for d in os.listdir(PROFILES_DIR)
                      if os.path.isdir(os.path.join(PROFILES_DIR, d)))
        if len(dirs) == 1:                 # only one profile: no ambiguity to resolve
            return dirs[0]
    return ""


def set_active(slug: str) -> None:
    os.makedirs(PROFILES_DIR, exist_ok=True)
    with open(ACTIVE_FILE, "w", encoding="utf-8") as fh:
        fh.write(slug.strip() + "\n")


def profile_dir() -> str:
    """Directory holding the active configuration — a profile, or the root."""
    slug = active_profile()
    if slug:
        return os.path.join(PROFILES_DIR, slug)
    if os.path.exists(os.path.join(ROOT, "config.yaml")):
        return ROOT                        # legacy layout, pre-profiles
    raise ProfileError(
        "No profile configured.\n"
        "Put your CV and transcripts in documents/ and run:  python3 setup.py")


def _load(name: str) -> dict:
    path = os.path.join(profile_dir(), name)
    if not os.path.exists(path):
        raise ProfileError(
            f"{name} missing from {os.path.relpath(profile_dir(), ROOT)}/.\n"
            f"Regenerate it with:  python3 setup.py --regenerate")
    with open(path, "r", encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def load_config() -> dict:
    return _load("config.yaml")


def load_companies() -> dict:
    return _load("companies.yaml")


def load_letters() -> dict:
    return _load("letters.yaml")


def load_taxonomy() -> dict:
    return _load("skills_taxonomy.yaml")


def load_narrative() -> dict:
    try:
        return _load("narrative.yaml")
    except ProfileError:
        return {}


def resolve(path: str) -> str:
    """Resolve a document path from the profile against the likely bases.

    Documents usually sit beside the project rather than inside it, so a path
    is tried against the project root and its parent before being given up on.
    """
    if not path:
        return ""
    if os.path.isabs(path):
        return path
    for base in (os.path.dirname(ROOT), ROOT, os.path.join(ROOT, "documents"), profile_dir()):
        cand = os.path.normpath(os.path.join(base, path))
        if os.path.exists(cand):
            return cand
    return os.path.normpath(os.path.join(os.path.dirname(ROOT), path))


def output_dir() -> str:
    """Per-profile output, so two people never share a job database."""
    slug = active_profile()
    d = os.path.join(ROOT, "output", slug) if slug else os.path.join(ROOT, "output")
    os.makedirs(d, exist_ok=True)
    return d
