"""`setup.py` — read someone's documents and generate their whole configuration.

The tool ships with no personal data. This turns a folder of documents into a
profile: which skill domains the person actually has evidence for, how postings
should be scored against them, which subjects their transcripts say they are
good at, what their cover letters should claim, and where to search.

    python3 setup.py                       # read ./documents (and the parent folder)
    python3 setup.py --documents ~/papers  # read somewhere else
    python3 setup.py --preset munich-deeptech
    python3 setup.py --regenerate          # rebuild configs from an edited profile.yaml
    python3 setup.py --list                # show profiles
    python3 setup.py --use anna-schmidt    # switch the active profile
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import sys

import yaml

from . import extract, profilegen as pg
from .config import ACTIVE_FILE, PROFILES_DIR, ROOT, active_profile, set_active

GENERATED = ("config.yaml", "letters.yaml", "skills_taxonomy.yaml",
             "companies.yaml", "narrative.yaml")


def _dump(obj) -> str:
    return yaml.safe_dump(obj, allow_unicode=True, sort_keys=False, width=100,
                          default_flow_style=False)


def _header(path: str, note: str) -> str:
    return (f"# {'=' * 68}\n"
            f"#  {os.path.basename(path)} — generated by setup.py\n"
            f"#\n"
            f"#  {note}\n"
            f"#  Edit freely: setup.py never overwrites a profile without --force,\n"
            f"#  and `--regenerate` rebuilds only from profile.yaml.\n"
            f"# {'=' * 68}\n\n")


NOTES = {
    "config.yaml": "Scoring rules: what a posting is worth to you and why.",
    "letters.yaml": "Cover-letter evidence, in your own words, taken from your CV.",
    "skills_taxonomy.yaml": "have / partial / gap per skill, for the gap analysis.",
    "companies.yaml": "Where to fetch postings from. Grow it with `run.py discover`.",
    "narrative.yaml": "Wording the generated reports use to talk about you.",
}


def _detect_cv_language(text: str) -> str:
    de = sum(text.lower().count(w) for w in
             (" und ", " der ", " die ", " mit ", " für ", "kenntnisse", "erfahrung"))
    en = sum(text.lower().count(w) for w in
             (" and ", " the ", " with ", " for ", "experience", "skills"))
    return "de" if de > en else "en"


def _place_names() -> set[str]:
    """Every city, suburb, region and country the ontology knows, so the name
    guesser never mistakes an address line for a person."""
    locs = pg.locations()
    names: set[str] = set()
    for spec in locs["metros"].values():
        names.update(a.lower() for a in spec.get("aliases", []))
        names.update(t.lower() for t in spec.get("towns", []))
        names.update(r.lower() for r in spec.get("region", []))
        names.update(e.lower() for e in spec.get("region_excludes", []))
    for spec in locs["countries"].values():
        names.update(n.lower() for n in spec.get("names", []))
    return names


def _load_preset(name: str) -> dict | None:
    path = os.path.join(ROOT, "presets", f"{name}.yaml")
    if not os.path.exists(path):
        print(f"  ! no preset '{name}' in presets/ — skipping")
        return None
    with open(path, "r", encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def _report_documents(docs) -> None:
    print("\nDocuments read")
    print("-" * 62)
    for d in docs:
        mark = {"cv": "CV", "transcript": "transcript", "certificate": "certificate",
                "reference": "reference", "other": "other",
                "unreadable": "UNREADABLE"}[d.kind]
        print(f"  {mark:<12} {d.name[:46]}")
    if any(d.kind == "unreadable" for d in docs):
        print("\n  ! An unreadable file is usually a scanned image. Install poppler-utils")
        print("    (`pdftotext`) if it is missing, or run OCR over the file first.")


def _report_profile(p: dict) -> None:
    ident, status = p["identity"], p["status"]
    print("\nWho this is")
    print("-" * 62)
    for k in ("full_name", "email", "phone", "city", "country"):
        val = ident.get(k) or "(not found)"
        print(f"  {k:<16} {val}")
    print(f"  {'career stage':<16} {status['career_stage']} "
          f"({status['years_experience']:g} yrs experience"
          f"{', student' if status['is_student'] else ''})")
    print(f"  {'languages':<16} " +
          (", ".join(f"{k} {v}" for k, v in (p.get('languages') or {}).items()) or "(none found)"))

    print("\nField, ranked by how much evidence your documents carry")
    print("-" * 62)
    for d in p["domains"]:
        print(f"  {d['weight']:>3}  {d['label']}")
        print(f"       {d['evidence'][0][:70]}")
    if not p["domains"]:
        print("  ! No domain matched. Check that the CV text extracted correctly.")

    ac = p["academic"]
    if ac["strong"] or ac["weak"]:
        print(f"\nTranscript signal (your own average = {ac['mean']:.2f})")
        print("-" * 62)
        for e in ac["strong"][:5]:
            print(f"  strong  {e['performance']:.2f}  {e['label']}")
        for e in ac["weak"][:5]:
            print(f"  weak    {e['performance']:.2f}  {e['label']}")

    levels: dict[str, int] = {}
    for spec in p["skills"].values():
        levels[spec["level"]] = levels.get(spec["level"], 0) + 1
    print(f"\nSkills: {levels.get('have', 0)} have, {levels.get('partial', 0)} partial, "
          f"{levels.get('gap', 0)} gap (across the whole ontology)")


def cmd_setup(args) -> int:
    folders = [args.documents] if args.documents else \
        [os.path.join(ROOT, "documents"), os.path.dirname(ROOT)]
    folders = [f for f in folders if os.path.isdir(f)]
    if not folders:
        print("No documents folder found. Put your CV and transcripts in "
              f"{os.path.join(ROOT, 'documents')}/ and run again.")
        return 1

    print(f"Reading documents from: {', '.join(folders)}")
    docs = extract.find_documents(folders)
    if not docs:
        print("No PDF, DOCX or text documents found there.")
        return 1
    _report_documents(docs)

    cv_docs = [d for d in docs if d.kind == "cv"]
    if not cv_docs:
        readable = [d for d in docs if d.kind not in ("unreadable",)]
        if not readable:
            print("\nNothing readable. A CV is required.")
            return 1
        cv_docs = [max(readable, key=lambda d: len(d.text))]
        print(f"\n  ! No file looked like a CV; using the longest document "
              f"({cv_docs[0].name}). Pass --documents with a cleaner folder if that is wrong.")

    gr = pg.grades()
    cv = extract.parse_cv(cv_docs[0].text, places=_place_names())
    transcripts = [extract.parse_transcript(d.text, gr["scales"], gr["non_courses"])
                   for d in docs if d.kind == "transcript"]
    transcripts = [t for t in transcripts if t.courses]
    if not transcripts:
        print("\n  ! No transcript parsed. Scoring will run on the CV alone — that "
              "works, but the graded strength/weakness layer will be empty.")

    root_for_paths = os.path.dirname(ROOT) if not args.documents else args.documents
    profile = pg.gather(cv, transcripts, docs, root_for_paths)
    if args.name:
        profile["identity"]["full_name"] = args.name
    _report_profile(profile)

    slug = args.slug or pg.slugify(profile["identity"]["full_name"] or "profile")
    target = os.path.join(PROFILES_DIR, slug)
    if os.path.exists(target) and not args.force:
        print(f"\nProfile '{slug}' already exists at profiles/{slug}/.")
        print("Re-run with --force to overwrite it, or --slug <name> to keep both.")
        return 1

    if not args.yes:
        print(f"\nThis will write profiles/{slug}/ and make it the active profile.")
        try:
            if input("Continue? [Y/n] ").strip().lower() in ("n", "no"):
                print("Nothing written.")
                return 1
        except EOFError:
            pass

    os.makedirs(target, exist_ok=True)
    cv_lang = _detect_cv_language(cv.all_text)
    preset = _load_preset(args.preset) if args.preset else None
    files = pg.generate(profile, cv_language=cv_lang, preset=preset)

    with open(os.path.join(target, "profile.yaml"), "w", encoding="utf-8") as fh:
        fh.write(_header("profile.yaml",
                         "Everything setup.py inferred from your documents. This is the\n"
                         "#  single source of truth — fix anything wrong here, then run\n"
                         "#  `python3 setup.py --regenerate`."))
        fh.write(_dump(profile))
    for name, obj in files.items():
        with open(os.path.join(target, name), "w", encoding="utf-8") as fh:
            fh.write(_header(name, NOTES[name]))
            fh.write(_dump(obj))

    set_active(slug)
    print(f"\nWritten to profiles/{slug}/")
    for n in ("profile.yaml",) + GENERATED:
        print(f"  {n}")
    print(f"\nActive profile is now '{slug}'.")
    _next_steps(profile, args.preset)
    return 0


def _next_steps(profile: dict, preset: str | None) -> None:
    steps = ["Skim profiles/<you>/profile.yaml, correct anything wrong, then:\n"
             "     python3 setup.py --regenerate"]
    if not preset:
        steps.append("Add employers to fetch from — either\n"
                     "        python3 run.py discover --url <a careers page>\n"
                     "        python3 setup.py --preset munich-deeptech   (if that fits)\n"
                     "     The aggregator sources already work without any of this.")
    steps += ["python3 run.py fetch", "python3 run.py review"]
    print("\nNext")
    print("-" * 62)
    for i, step in enumerate(steps, 1):
        print(f"  {i}. {step}")


def cmd_regenerate(args) -> int:
    slug = args.slug or active_profile()
    if not slug:
        print("No active profile. Run: python3 setup.py")
        return 1
    target = os.path.join(PROFILES_DIR, slug)
    path = os.path.join(target, "profile.yaml")
    if not os.path.exists(path):
        print(f"profiles/{slug}/profile.yaml not found.")
        return 1
    with open(path, "r", encoding="utf-8") as fh:
        profile = yaml.safe_load(fh)

    preset = _load_preset(args.preset) if args.preset else None
    if not preset:
        # Keep hand-added employers: regeneration must not wipe the registry.
        existing = os.path.join(target, "companies.yaml")
        if os.path.exists(existing):
            with open(existing, "r", encoding="utf-8") as fh:
                prev = yaml.safe_load(fh) or {}
            preset = {k: v for k, v in prev.items()
                      if k not in ("adzuna", "arbeitnow", "jsearch", "jooble") and v}

    files = pg.generate(profile, preset=preset)
    kept = _carry_keys(os.path.join(target, "config.yaml"), files["config.yaml"])
    for name, obj in files.items():
        with open(os.path.join(target, name), "w", encoding="utf-8") as fh:
            fh.write(_header(name, NOTES[name]))
            fh.write(_dump(obj))
    print(f"Regenerated {', '.join(files)} in profiles/{slug}/ from profile.yaml.")
    if kept:
        print(f"Kept your existing API key(s): {', '.join(kept)}.")
    return 0


KEY_FIELDS = {"adzuna": ("app_id", "app_key"), "jsearch": ("api_key",),
              "jooble": ("api_key",)}


def _carry_keys(existing_path: str, new_cfg: dict) -> list[str]:
    """Regeneration rebuilds config.yaml from scratch, which would otherwise
    throw away credentials the user pasted in by hand."""
    if not os.path.exists(existing_path):
        return []
    with open(existing_path, "r", encoding="utf-8") as fh:
        old = yaml.safe_load(fh) or {}
    kept = []
    for section, fields in KEY_FIELDS.items():
        for field in fields:
            value = (old.get(section) or {}).get(field)
            if value and not (new_cfg.get(section) or {}).get(field):
                new_cfg.setdefault(section, {})[field] = value
                kept.append(f"{section}.{field}")
    return kept


def cmd_list(args) -> int:
    active = active_profile()
    if not os.path.isdir(PROFILES_DIR):
        print("No profiles yet. Run: python3 setup.py")
        return 0
    names = sorted(d for d in os.listdir(PROFILES_DIR)
                   if os.path.isdir(os.path.join(PROFILES_DIR, d)))
    if not names:
        print("No profiles yet. Run: python3 setup.py")
        return 0
    for n in names:
        cfg = os.path.join(PROFILES_DIR, n, "config.yaml")
        who = ""
        if os.path.exists(cfg):
            with open(cfg, "r", encoding="utf-8") as fh:
                data = yaml.safe_load(fh) or {}
            who = (data.get("profile") or {}).get("headline", "")
        print(f"  {'*' if n == active else ' '} {n:<24} {who[:52]}")
    print("\n  * = active.  Switch with: python3 setup.py --use <name>")
    return 0


def cmd_use(args) -> int:
    target = os.path.join(PROFILES_DIR, args.use)
    if not os.path.isdir(target):
        print(f"No profile '{args.use}'. See: python3 setup.py --list")
        return 1
    set_active(args.use)
    print(f"Active profile is now '{args.use}'.")
    return 0


def cmd_preset_only(args) -> int:
    """Apply a preset registry to the active profile without re-reading documents."""
    slug = active_profile()
    if not slug:
        print("No active profile. Run: python3 setup.py")
        return 1
    preset = _load_preset(args.preset)
    if preset is None:
        return 1
    path = os.path.join(PROFILES_DIR, slug, "companies.yaml")
    with open(path, "r", encoding="utf-8") as fh:
        current = yaml.safe_load(fh) or {}
    added = 0
    for ats, entries in preset.items():
        if not entries:
            continue
        have = {e["slug"] for e in current.get(ats, []) or []}
        for e in entries:
            if e["slug"] not in have:
                current.setdefault(ats, []).append(e)
                added += 1
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(_header("companies.yaml", NOTES["companies.yaml"]))
        fh.write(_dump(current))
    print(f"Added {added} employer(s) from preset '{args.preset}' to profiles/{slug}/companies.yaml.")
    return 0


def main(argv=None) -> int:
    p = argparse.ArgumentParser(
        prog="setup.py",
        description="Read a CV and transcripts, and generate a personal jobbot config.")
    p.add_argument("--documents", help="folder holding the CV and transcripts")
    p.add_argument("--name", help="override the name read from the CV")
    p.add_argument("--slug", help="profile folder name (default: from the name)")
    p.add_argument("--preset", help="company registry preset from presets/")
    p.add_argument("--regenerate", action="store_true",
                   help="rebuild configs from an edited profile.yaml")
    p.add_argument("--list", action="store_true", help="list profiles")
    p.add_argument("--use", help="make a profile active")
    p.add_argument("--force", action="store_true", help="overwrite an existing profile")
    p.add_argument("-y", "--yes", action="store_true", help="do not ask for confirmation")
    args = p.parse_args(argv)

    if args.list:
        return cmd_list(args)
    if args.use:
        return cmd_use(args)
    if args.regenerate:
        return cmd_regenerate(args)
    # `setup.py --preset X` on its own means "add these employers to the
    # profile I already have". Combined with any other flag it is part of a
    # full run instead.
    alone = not (args.documents or args.force or args.name or args.slug)
    if args.preset and alone and active_profile() and \
            os.path.exists(os.path.join(PROFILES_DIR, active_profile(), "companies.yaml")):
        return cmd_preset_only(args)
    return cmd_setup(args)
